receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

extensions:
  # responsible for responding to health check calls on behalf of the collector.
  health_check:
  # fetches the collector’s performance data
  pprof:

service:
  extensions: [health_check, pprof]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
